--liquibase formatted sql

--changeset vincent2704:001-create-product-and-orders-tables
--comment: Create draft product and order tables as first migration
CREATE TABLE products (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        status VARCHAR(255)
);

--rollback DROP TABLE orders;
--rollback DROP TABLE products;
